=== mmontes-vicente/LENGUAJE_DE_MARCAS/Practicas/DAW-LM-BibliotecaXML-main/tienda.dtd
<!ELEMENT tienda (productos, pedidos)>

<!ELEMENT productos (producto+)>

<!ELEMENT producto (nombre, precio)>
<!ATTLIST producto 
idProd ID #REQUIRED
>

<!ELEMENT pedidos (pedido+)>

<!ELEMENT pedido (productoRef, cantidad)>
<!ATTLIST pedido 
idPedido ID #REQUIRED
>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

<!ELEMENT productoRef (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>

=== mmontes-vicente/LENGUAJE_DE_MARCAS/Practicas/DAW-LM-BibliotecaXML-main/tienda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tienda SYSTEM "tienda.dtd"[
]>

<tienda>
    <productos>
        <producto idProd="p1">
            <nombre>Teclado</nombre>
            <precio>10</precio>
        </producto>

        <producto idProd="p2">
            <nombre>Teclado</nombre>
            <precio>10</precio>
        </producto>

    </productos>

    <pedidos>
        <pedido idPedido="ped1">
            <productoRef>p2</productoRef>
            <cantidad>2</cantidad>
        </pedido>

    </pedidos>

</tienda>
